
server:
  port: 8080

eureka:
  instance:
   hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-1
          uri: http://localhost:8085/
          predicates: 
          - Path=/user-service/**